USE [master]
GO
/****** Object:  Database [33Whales]    Script Date: 22.12.2017 21:51:30 ******/
CREATE DATABASE [33Whales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'33Whales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\33Whales.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [33Whales_FileGroup] CONTAINS FILESTREAM  DEFAULT
( NAME = N'33Whales_Files', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\33Whales_Files' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'33Whales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\33Whales_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [33Whales] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [33Whales].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [33Whales] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [33Whales] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [33Whales] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [33Whales] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [33Whales] SET ARITHABORT OFF 
GO
ALTER DATABASE [33Whales] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [33Whales] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [33Whales] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [33Whales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [33Whales] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [33Whales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [33Whales] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [33Whales] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [33Whales] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [33Whales] SET  DISABLE_BROKER 
GO
ALTER DATABASE [33Whales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [33Whales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [33Whales] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [33Whales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [33Whales] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [33Whales] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [33Whales] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [33Whales] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [33Whales] SET  MULTI_USER 
GO
ALTER DATABASE [33Whales] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [33Whales] SET DB_CHAINING OFF 
GO
ALTER DATABASE [33Whales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [33Whales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [33Whales] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [33Whales] SET QUERY_STORE = OFF
GO
USE [33Whales]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [33Whales]
GO
/****** Object:  Table [dbo].[CompositionOfMenus]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CompositionOfMenus](
	[MenuID] [int] NOT NULL,
	[RecipeID] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[PricePerUnit] [money] NOT NULL,
 CONSTRAINT [PK_CompositionOfMenus] PRIMARY KEY CLUSTERED 
(
	[MenuID] ASC,
	[RecipeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CompositionOfRecipes]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CompositionOfRecipes](
	[RecipeID] [int] NOT NULL,
	[IngredientID] [int] NOT NULL,
	[Quantity] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_CompositionOfRecipes] PRIMARY KEY CLUSTERED 
(
	[RecipeID] ASC,
	[IngredientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IngredientPictures]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IngredientPictures](
	[IngredientPictureID] [int] IDENTITY(1,1) NOT NULL,
	[IngredientID] [int] NOT NULL,
	[IngrFilePicId] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[Picture] [varbinary](max) FILESTREAM  NOT NULL,
 CONSTRAINT [PK_IngredientPictures] PRIMARY KEY CLUSTERED 
(
	[IngredientPictureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] FILESTREAM_ON [33Whales_FileGroup],
UNIQUE NONCLUSTERED 
(
	[IngrFilePicId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] FILESTREAM_ON [33Whales_FileGroup]
GO
/****** Object:  Table [dbo].[Ingredients]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredients](
	[IngredientID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Ingredients] PRIMARY KEY CLUSTERED 
(
	[IngredientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Menus]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menus](
	[MenuID] [int] IDENTITY(1,1) NOT NULL,
	[Date] [date] NOT NULL,
 CONSTRAINT [PK_Menus] PRIMARY KEY CLUSTERED 
(
	[MenuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Prices]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prices](
	[IngredientID] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[PricePerUnit] [money] NOT NULL,
	[Unit] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Prices] PRIMARY KEY CLUSTERED 
(
	[IngredientID] ASC,
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecipePictures]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecipePictures](
	[RecipePictureID] [int] IDENTITY(1,1) NOT NULL,
	[RecipeID] [int] NOT NULL,
	[IngrFilePicId] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[Picture] [varbinary](max) FILESTREAM  NOT NULL,
 CONSTRAINT [PK_RecipePictures] PRIMARY KEY CLUSTERED 
(
	[RecipePictureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] FILESTREAM_ON [33Whales_FileGroup],
UNIQUE NONCLUSTERED 
(
	[IngrFilePicId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] FILESTREAM_ON [33Whales_FileGroup]
GO
/****** Object:  Table [dbo].[Recipes]    Script Date: 22.12.2017 21:51:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipes](
	[RecipeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[FinishedProduct] [int] NOT NULL,
 CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED 
(
	[RecipeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IngredientPictures] ADD  CONSTRAINT [DF_IngredientPictures_IngrFilePicId]  DEFAULT (newid()) FOR [IngrFilePicId]
GO
ALTER TABLE [dbo].[RecipePictures] ADD  CONSTRAINT [DF_RecipePictures_IngrFilePicId]  DEFAULT (newid()) FOR [IngrFilePicId]
GO
ALTER TABLE [dbo].[CompositionOfMenus]  WITH CHECK ADD  CONSTRAINT [FK_CompositionOfMenus_Menus] FOREIGN KEY([MenuID])
REFERENCES [dbo].[Menus] ([MenuID])
GO
ALTER TABLE [dbo].[CompositionOfMenus] CHECK CONSTRAINT [FK_CompositionOfMenus_Menus]
GO
ALTER TABLE [dbo].[CompositionOfMenus]  WITH CHECK ADD  CONSTRAINT [FK_CompositionOfMenus_Recipes] FOREIGN KEY([RecipeID])
REFERENCES [dbo].[Recipes] ([RecipeID])
GO
ALTER TABLE [dbo].[CompositionOfMenus] CHECK CONSTRAINT [FK_CompositionOfMenus_Recipes]
GO
ALTER TABLE [dbo].[CompositionOfRecipes]  WITH CHECK ADD  CONSTRAINT [FK_CompositionOfRecipes_Ingredients] FOREIGN KEY([IngredientID])
REFERENCES [dbo].[Ingredients] ([IngredientID])
GO
ALTER TABLE [dbo].[CompositionOfRecipes] CHECK CONSTRAINT [FK_CompositionOfRecipes_Ingredients]
GO
ALTER TABLE [dbo].[CompositionOfRecipes]  WITH CHECK ADD  CONSTRAINT [FK_CompositionOfRecipes_Recipes] FOREIGN KEY([RecipeID])
REFERENCES [dbo].[Recipes] ([RecipeID])
GO
ALTER TABLE [dbo].[CompositionOfRecipes] CHECK CONSTRAINT [FK_CompositionOfRecipes_Recipes]
GO
ALTER TABLE [dbo].[IngredientPictures]  WITH CHECK ADD  CONSTRAINT [FK_IngredientPictures_Ingredients] FOREIGN KEY([IngredientID])
REFERENCES [dbo].[Ingredients] ([IngredientID])
GO
ALTER TABLE [dbo].[IngredientPictures] CHECK CONSTRAINT [FK_IngredientPictures_Ingredients]
GO
ALTER TABLE [dbo].[Prices]  WITH CHECK ADD  CONSTRAINT [FK_Prices_Ingredients] FOREIGN KEY([IngredientID])
REFERENCES [dbo].[Ingredients] ([IngredientID])
GO
ALTER TABLE [dbo].[Prices] CHECK CONSTRAINT [FK_Prices_Ingredients]
GO
ALTER TABLE [dbo].[RecipePictures]  WITH CHECK ADD  CONSTRAINT [FK_RecipePictures_Recipes] FOREIGN KEY([RecipeID])
REFERENCES [dbo].[Recipes] ([RecipeID])
GO
ALTER TABLE [dbo].[RecipePictures] CHECK CONSTRAINT [FK_RecipePictures_Recipes]
GO
USE [master]
GO
ALTER DATABASE [33Whales] SET  READ_WRITE 
GO
